color0 #241f31
color1 #c01c28
color2 #2ec27e
color3 #f5c211
color4 #1e78e4
color5 #9841bb
color6 #0ab9dc
color7 #c0bfbc
color8 #5e5c64
color9 #ed333b
color10 #57e389
color11 #f8e45c
color12 #51a1ff
color13 #c061cb
color14 #4fd2fd
color15 #ffffff

cursor                #3584e4
cursor_text_color     #d6d7d7
background            #000000
foreground            #ffffff
selection_foreground  #ffffff
selection_background  #3584e4
active_border_color   #3584e4
inactive_border_color #000000
url_color             #3584e4

active_tab_foreground   #ffffff
active_tab_background   #3584e4
inactive_tab_foreground #ffffff
inactive_tab_background #000000
cursor_trail_color      #ffffff
